trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: pipeline_templates
      type: github
      name: gsreynolds/azuredevops_chef_pipeline_templates
      endpoint: github.com

variables:
  CHEF_ENDPOINT: 'Chef Service Connection Name Here'

stages:
- template: stage_chefrepo_lint.yml@pipeline_templates
- template: stage_chefrepo_upload.yml@pipeline_templates
