trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: pipeline_templates
      type: github
      name: gsreynolds/azuredevops_chef_pipeline_templates
      endpoint: github.com


stages:
- template: stage_cookbook_prep.yml@pipeline_templates
  parameters: { Berksfile: true }
- template: stage_cookbook_lintunit.yml@pipeline_templates
  parameters: { Berksfile: true }

- stage: Testing
  jobs:
  - job: TestKitchenAzure
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Berksfile.lock Pipeline Artifact'
      inputs:
        artifact: 'BerksfileLock'
        path: $(Build.SourcesDirectory)
    - template: steps_kitchen_test_azure.yml@pipeline_templates
  # - job: TestKitchenvSphere
  #   steps:
  #   - task: DownloadPipelineArtifact@2
  #     displayName: 'Download Berksfile.lock Pipeline Artifact'
  #     inputs:
  #       artifact: 'BerksfileLock'
  #       path: $(Build.SourcesDirectory)
  #   - template: steps_kitchen_test_vsphere.yml@pipeline_templates

- template: stage_cookbook_release.yml@pipeline_templates
  parameters: { Berksfile: true }
