
stages:
- stage: ChefRepoLint
  jobs:
  - job: JSONLint
    steps:
    - template: steps_chefrepo_jsonlint.yml@pipeline_templates

  - job: EnvironmentsCookbookVersionsCheck
    steps:
      - template: steps_chefrepo_env_cookbook_versions_check.yml@pipeline_templates

