stages:
- stage: ChefRepoUpload
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Upload
    steps:
    - template: steps_chef_workstation_install.yml@pipeline_templates
    - template: steps_knife_config.yml@pipeline_templates
    - template: steps_chefrepo_knife_config.yml@pipeline_templates
    - template: steps_chefrepo_upload.yml@pipeline_templates
