steps:
- task: chef-software.chef-azdo.helpers.helper@3
  displayName: 'Configure Knife'
  inputs:
    helper: 'setupChef'
    chefendpoint: $(CHEF_ENDPOINT)

# - task: DownloadSecureFile@1
#   name: credentials
#   displayName: 'Download credentials'
#   inputs:
#     secureFile: 'credentials'

# - task: DownloadSecureFile@1
#   name: greynoldspem
#   displayName: 'Download greynolds.pem'
#   inputs:
#     secureFile: 'greynolds.pem'

# - task: CmdLine@2
#   displayName: 'Configure Chef Repo'
#   inputs:
#     script: |
#       mkdir ~/.chef
#       mv $(credentials.secureFilePath) ~/.chef
#       mv $(greynoldspem.secureFilePath) ~/.chef
#       ls ~/.chef

# - task: chef-software.chef-azdo.execute.component@3
#   displayName: 'Knife List Profiles'
#   inputs:
#     component: 'knife'
#     arguments: 'config list-profiles'

- task: chef-software.chef-azdo.execute.component@3
  displayName: 'Knife Config Show'
  inputs:
    component: 'knife'
    arguments: 'config show'
